version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DEBUG=dental_practice:*
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
